apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: coiwopuf6-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c676da61070465e1154993fe516bf935dbfef9e6@sha256:20d38174ebe7c8d1ef203b184b50bf908e4362b91f97f54c84941fa5a00ba1aa
          name: container-image
